apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  # DB가 설치된 'database' 네임스페이스에 생성
  namespace: database 
type: Opaque
stringData:
  DB_USER: "harman_user"
  DB_PASS: "harman_pass"
  DB_NAME: "harman_db"
  # K8s 내부 DNS 주소: <서비스명>.<네임스페이스>.svc.cluster.local
  DB_HOST: "harman-db-postgresql.database.svc.cluster.local" 
